kind: pipeline
name: sass-fire.io

steps:
  - name: install dependencies
    image: node
    commands:
      - yarn

  - name: document
    image: node
    commands:
      - yarn document

  - name: deploy
    image: node
    environment:
      GH_TOKEN:
        from_secret: GH_TOKEN
    commands:
      - git config --global user.email "73201+jackw@users.noreply.github.com"
      - git config --global user.name "jackw"
      - yarn deploy
    when:
      branch: master
      event: push

  - name: commit data
    image: node
    environment:
      GH_TOKEN:
        from_secret: GH_TOKEN
    commands:
      - git config --global user.email "73201+jackw@users.noreply.github.com"
      - git config --global user.name "jackw"
      - git add src/data/sassfire
      - git diff-index --quiet HEAD || git commit -m "ci - add latest json"
      - git push
    when:
      branch: master
      event: push
