kind: pipeline
name: sass-fire.io

steps:
  - name: install dependencies
    image: node
    commands:
      - yarn

  - name: document
    image: node
    commands:
      - yarn document

  - name: deploy
    image: node
    environment:
      GH_TOKEN:
        from_secret: GH_TOKEN
    commands:
      - git config --global user.email "73201+jackw@users.noreply.github.com"
      - git config --global user.name "jackw"
      - yarn deploy

  - name: commit data
    image: node
    environment:
      GH_TOKEN:
        from_secret: GH_TOKEN
    commands:
      - git config --global user.email "73201+jackw@users.noreply.github.com"
      - git config --global user.name "jackw"
      - git config --global credential.helper store
      - echo "https://$GH_TOKEN:x-oauth-basic@github.com" > $HOME\.git-credentials
      - git add src/data/sassfire
      - git commit -m "ci(publish) - add latest json"
      - git push
